# Natours

###
# group: Users
# @name Get users
# This is a GET request and it is used to "get" data from an endpoint. There is no request body for a GET request, but you can use query parameters to help specify the resource you want data on (e.g., in this request, we have `id=1`).
# A successful GET response will have a `200 OK` status, and should include some kind of response body - for example, HTML web content or JSON data.
GET {{base_url}}/users

> {%
  // TODO: migrate to HTTP Client Response handler API
  // pm.test("Status code is 200", function () {
  //     pm.response.to.have.status(200);
  // });
%}

###
# group: Users
# @name Post user
# This is a POST request, submitting data to an API via the request body. This request submits JSON data, and the data is reflected in the response.
# A successful POST request typically returns a `200 OK` or `201 Created` response code.
POST {{base_url}}/info
Content-Type: application/json

{
  "name": "Add your name in the body"
}

> {%
  // TODO: migrate to HTTP Client Response handler API
  // pm.test("Successful POST request", function () {
  //     pm.expect(pm.response.code).to.be.oneOf([200, 201]);
  // });
  //
%}

###
# group: Users
# @name Sign up
# This is a POST request, submitting data to an API via the request body. This request submits JSON data, and the data is reflected in the response.
# A successful POST request typically returns a `200 OK` or `201 Created` response code.
POST {{base_url}}/users/signup
Content-Type: application/json

{
  "name": "Guide",
  "email": "testMail2@gmail.com",
  "password": "password123",
  "passwordConfirm": "password123",
  "role": "guide"
}

> {%
  // TODO: migrate to HTTP Client Response handler API
  // pm.test("Successful POST request", function () {
  //     pm.expect(pm.response.code).to.be.oneOf([200, 201]);
  // });
  //
%}

###
# group: Users
# @name Login admin
# This is a POST request, submitting data to an API via the request body. This request submits JSON data, and the data is reflected in the response.
# A successful POST request typically returns a `200 OK` or `201 Created` response code.
//< {%
    // TODO: you can add here Pre-request handler
//%}
POST {{base_url}}/users/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "admin!23"
}

> {%
  // TODO: migrate to HTTP Client Response handler API
  // pm.test("Successful POST request", function () {
  //     pm.expect(pm.response.code).to.be.oneOf([200, 201]);
  //     pm.environment.set("jwt", pm.response.json().token);
  // });
  //
%}

###
# group: Users
# @name Login user
# This is a POST request, submitting data to an API via the request body. This request submits JSON data, and the data is reflected in the response.
# A successful POST request typically returns a `200 OK` or `201 Created` response code.
//< {%
    // TODO: you can add here Pre-request handler
//%}
POST {{base_url}}/users/login
Content-Type: application/json

{
  "email": "testMail@gmail.com",
  "password": "secret1234"
}

> {%
  // TODO: migrate to HTTP Client Response handler API
  // pm.test("Successful POST request", function () {
  //     pm.expect(pm.response.code).to.be.oneOf([200, 201]);
  //     pm.environment.set("jwt", pm.response.json().token);
  // });
  //
%}

###
# group: Users
# @name Login admin by query injection
# This is a POST request, submitting data to an API via the request body. This request submits JSON data, and the data is reflected in the response.
# A successful POST request typically returns a `200 OK` or `201 Created` response code.
//< {%
    // TODO: you can add here Pre-request handler
//%}
POST {{base_url}}/users/login
Content-Type: application/json

{
  "email": {
    "$gt": ""
  },
  "password": "admin!23"
}

> {%
  // TODO: migrate to HTTP Client Response handler API
  // pm.test("Successful POST request", function () {
  //     pm.expect(pm.response.code).to.be.oneOf([200, 201]);
  //     pm.environment.set("jwt", pm.response.json().token);
  // });
  //
%}

###
# group: Users
# @name 1) Forgot password
# This is a POST request, submitting data to an API via the request body. This request submits JSON data, and the data is reflected in the response.
# A successful POST request typically returns a `200 OK` or `201 Created` response code.
//< {%
    // TODO: you can add here Pre-request handler
//%}
POST {{base_url}}/users/forgotPassword
Content-Type: application/json

{
  "email": "testMail@gmail.com"
}

> {%
  // TODO: migrate to HTTP Client Response handler API
  // pm.test("Successful POST request", function () {
  //     pm.expect(pm.response.code).to.be.oneOf([200, 201]);
  //     pm.environment.set("jwt", pm.response.json().token);
  // });
  //
%}

###
# group: Users
# @name 2) Reset password
# This is a POST request, submitting data to an API via the request body. This request submits JSON data, and the data is reflected in the response.
# A successful POST request typically returns a `200 OK` or `201 Created` response code.
//< {%
    // TODO: you can add here Pre-request handler
//%}
PATCH {{base_url}}/users/resetPassword/ddd36b1de93707bbef6791f1d2e9ce0c158c5d7c3b07be3840da02f4f87b3d19
Content-Type: application/json

{
  "password": "secret1234",
  "passwordConfirm": "secret1234"
}

> {%
  // TODO: migrate to HTTP Client Response handler API
  // pm.test("Successful POST request", function () {
  //     pm.expect(pm.response.code).to.be.oneOf([200, 201]);
  //     pm.environment.set("jwt", pm.response.json().token);
  // });
  //
%}

###
# group: Users
# @name Update password
# This is a POST request, submitting data to an API via the request body. This request submits JSON data, and the data is reflected in the response.
# A successful POST request typically returns a `200 OK` or `201 Created` response code.
//< {%
    // TODO: you can add here Pre-request handler
//%}
PATCH {{base_url}}/users/updatePassword
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "email": "testMail@gmail.com",
  "password": "secret1234",
  "passwordConfirm": "secret1234",
  "newPasswordConfirm": "123"
}

> {%
  // TODO: migrate to HTTP Client Response handler API
  // pm.test("Successful POST request", function () {
  //     pm.expect(pm.response.code).to.be.oneOf([200, 201]);
  //     pm.environment.set("jwt", pm.response.json().token);
  // });
  //
%}

###
# group: Users
# @name Update user
# This is a PUT request and it is used to overwrite an existing piece of data. For instance, after you create an entity with a POST request, you may want to modify that later. You can do that using a PUT request. You typically identify the entity being updated by including an identifier in the URL (eg. `id=1`).
# A successful PUT request typically returns a `200 OK`, `201 Created`, or `204 No Content` response code.
PUT {{base_url}}/info?
    id=1
Content-Type: application/json

{
  "name": "Add your name in the body"
}

> {%
  // TODO: migrate to HTTP Client Response handler API
  // pm.test("Successful PUT request", function () {
  //     pm.expect(pm.response.code).to.be.oneOf([200, 201, 204]);
  // });
  //
%}

###
# group: Users
# @name Delete user
# This is a DELETE request, and it is used to delete data that was previously created via a POST request. You typically identify the entity being updated by including an identifier in the URL (eg. `id=1`).
# A successful DELETE request typically returns a `200 OK`, `202 Accepted`, or `204 No Content` response code.
DELETE {{base_url}}/info?
    id=1

> {%
  // TODO: migrate to HTTP Client Response handler API
  // pm.test("Successful DELETE request", function () {
  //     pm.expect(pm.response.code).to.be.oneOf([200, 202, 204]);
  // });
  //
%}

###
# group: Tours
# @name Get ALL tours
# This is a GET request and it is used to "get" data from an endpoint. There is no request body for a GET request, but you can use query parameters to help specify the resource you want data on (e.g., in this request, we have `id=1`).
# A successful GET response will have a `200 OK` status, and should include some kind of response body - for example, HTML web content or JSON data.
GET {{base_url}}/tours
Authorization: Bearer {{jwt}}

> {%
  // TODO: migrate to HTTP Client Response handler API
  // pm.test("Status code is 200", function () {
  //     pm.response.to.have.status(200);
  // });
%}

###
# group: Tours
# @name Get monthly plan
# This is a GET request and it is used to "get" data from an endpoint. There is no request body for a GET request, but you can use query parameters to help specify the resource you want data on (e.g., in this request, we have `id=1`).
# A successful GET response will have a `200 OK` status, and should include some kind of response body - for example, HTML web content or JSON data.
GET {{base_url}}/tours/monthly-plan/2021

> {%
  // TODO: migrate to HTTP Client Response handler API
  // pm.test("Status code is 200", function () {
  //     pm.response.to.have.status(200);
  // });
%}

###
# group: Tours
# @name Get tours
# This is a GET request and it is used to "get" data from an endpoint. There is no request body for a GET request, but you can use query parameters to help specify the resource you want data on (e.g., in this request, we have `id=1`).
# A successful GET response will have a `200 OK` status, and should include some kind of response body - for example, HTML web content or JSON data.
GET {{base_url}}/tours?
    difficulty=medium&
    duration[lt]=10&
    sort=-price,duration&
    fields=-description&
    limit=4&
    page=1&
    any=medium

> {%
  // TODO: migrate to HTTP Client Response handler API
  // pm.test("Status code is 200", function () {
  //     pm.response.to.have.status(200);
  // });
%}

###
# group: Tours
# @name Get top 5
# This is a GET request and it is used to "get" data from an endpoint. There is no request body for a GET request, but you can use query parameters to help specify the resource you want data on (e.g., in this request, we have `id=1`).
# A successful GET response will have a `200 OK` status, and should include some kind of response body - for example, HTML web content or JSON data.
GET {{base_url}}/tours/top-5-cheap

> {%
  // TODO: migrate to HTTP Client Response handler API
  // pm.test("Status code is 200", function () {
  //     pm.response.to.have.status(200);
  // });
%}

###
# group: Tours
# @name Get stats
# This is a GET request and it is used to "get" data from an endpoint. There is no request body for a GET request, but you can use query parameters to help specify the resource you want data on (e.g., in this request, we have `id=1`).
# A successful GET response will have a `200 OK` status, and should include some kind of response body - for example, HTML web content or JSON data.
GET {{base_url}}/tours/stats

> {%
  // TODO: migrate to HTTP Client Response handler API
  // pm.test("Status code is 200", function () {
  //     pm.response.to.have.status(200);
  // });
%}

###
# group: Tours
# @name Get tour
# This is a GET request and it is used to "get" data from an endpoint. There is no request body for a GET request, but you can use query parameters to help specify the resource you want data on (e.g., in this request, we have `id=1`).
# A successful GET response will have a `200 OK` status, and should include some kind of response body - for example, HTML web content or JSON data.
GET {{base_url}}/tours/69aaffbb4e7aabd8d3804338

> {%
  // TODO: migrate to HTTP Client Response handler API
  // pm.test("Status code is 200", function () {
  //     pm.response.to.have.status(200);
  // });
%}

###
# group: Tours
# @name Post tour
# This is a POST request, submitting data to an API via the request body. This request submits JSON data, and the data is reflected in the response.
# A successful POST request typically returns a `200 OK` or `201 Created` response code.
POST {{base_url}}/tours
Content-Type: application/json

{
  "name": "New disco asdas",
  "duration": 7,
  "maxGroupSize": 15,
  "difficulty": "medium",
  "ratingsAverage": 4.8,
  "ratingsQuantity": 23,
  "price": 497,
  "priceDiscount": 32,
  "summary": "Exploring the jaw-dropping US east coast by foot and by boat",
  "description": "Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\nIrure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  "imageCover": "tour-2-cover.jpg",
  "images": [
    "tour-2-1.jpg",
    "tour-2-2.jpg",
    "tour-2-3.jpg"
  ],
  "startDates": [
    "2021-06-19,10:00",
    "2021-07-20,10:00",
    "2021-08-18,10:00"
  ],
  "secretTour": true
}

> {%
  // TODO: migrate to HTTP Client Response handler API
  // pm.test("Successful POST request", function () {
  //     pm.expect(pm.response.code).to.be.oneOf([200, 201]);
  // });
  //
%}

###
# group: Tours
# @name Delete tour
# This is a DELETE request, and it is used to delete data that was previously created via a POST request. You typically identify the entity being updated by including an identifier in the URL (eg. `id=1`).
# A successful DELETE request typically returns a `200 OK`, `202 Accepted`, or `204 No Content` response code.
DELETE {{base_url}}/tours/69b29dca9e9bd9e2f6d538e6

> {%
  // TODO: migrate to HTTP Client Response handler API
  // pm.test("Successful DELETE request", function () {
  //     pm.expect(pm.response.code).to.be.oneOf([200, 202, 204]);
  // });
  //
%}

###
# group: Tours
# @name Update tour
# This is a PUT request and it is used to overwrite an existing piece of data. For instance, after you create an entity with a POST request, you may want to modify that later. You can do that using a PUT request. You typically identify the entity being updated by including an identifier in the URL (eg. `id=1`).
# A successful PUT request typically returns a `200 OK`, `201 Created`, or `204 No Content` response code.
PUT {{base_url}}/info?
    id=1
Content-Type: application/json

{
  "name": "Add your name in the body"
}

> {%
  // TODO: migrate to HTTP Client Response handler API
  // pm.test("Successful PUT request", function () {
  //     pm.expect(pm.response.code).to.be.oneOf([200, 201, 204]);
  // });
  //
%}

###
# group: Tours
# @name Patch tour
PATCH {{base_url}}/tours/69a84800b347689401e09fa1
Content-Type: application/json

{
  "price": 449
}